enum ActionType {
  NEXT = 'NEXT',
  GOTO_ROOT = 'GOTO_ROOT',
  GOTO_JOIN = 'GOTO_JOIN',
  COMMAND = 'COMMAND',
  HELP = 'HELP',
  C_CLEAR = 'C_CLEAR',
  JOIN = 'JOIN',
  JOIN_ACCEPTED = 'JOIN_ACCEPTED',
  JOIN_DENIED = 'JOIN_DENIED',
  COUNT_CLAIMS = 'COUNT_CLAIMS',
}

export default ActionType;
