enum ActionType {
  SET_SUBSCRIPTION = 'SET_SUBSCRIPTION',
  SUBSCRIBE = 'SUBSCRIBE',
  UNSUBSCRIBE = 'UNSUBSCRIBE',
  RESET_STATUS = 'RESET_STATUS',
  STATUS_CHANGED = 'STATUS_CHANGED',
}

export default ActionType;
