enum ActionTypeTerminalApp {
  SET_APP_LOADER = 'SET_APP_LOADER',
  SET_APP_HYDRATION = 'SET_APP_HYDRATION',
  PLAY_VIDEO = 'PLAY_VIDEO',
  SET_VISITED = 'SET_VISITED',
  SET_CLAIMED_COUNT = 'SET_CLAIMED_COUNT',
  INIT_COUNTER = 'INIT_COUNTER',
  RESET_COUNTER = 'RESET_COUNTER',
  INC_CLAIMED_COUNT = 'INC_CLAIMED_COUNT',
}

export default ActionTypeTerminalApp;
