enum ActionTypeTerminalApp {
  SET_APP_LOADER = 'SET_APP_LOADER',
  SET_APP_HYDRATION = 'SET_APP_HYDRATION',
  PLAY_VIDEO = 'PLAY_VIDEO',
  SET_VISITED = 'SET_VISITED',
  SET_ALL_CLAIMED = 'SET_ALL_CLAIMED',
}

export default ActionTypeTerminalApp;
