enum ActionTypeTerminalApp {
  SET_APP_LOADER = 'SET_APP_LOADER',
  SET_APP_HYDRATION = 'SET_APP_HYDRATION',
  PLAY_VIDEO = 'PLAY_VIDEO',
  SET_CLAIM_OBJECT = 'SET_CLAIM_OBJECT',
  SET_SUBSCRIPTION_OBJECT = 'SET_SUBSCRIPTION_OBJECT',
  SET_USER = 'SET_USER',
}

export default ActionTypeTerminalApp;
