enum ActionType {
  SET_SUBSCRIPTION = 'SET_SUBSCRIPTION',
  SUBSCRIBE = 'SUBSCRIBE',
  UNSUBSCRIBE = 'UNSUBSCRIBE',
  SET_CONNECTION = 'SET_CONNECTION',
  CONNECT_WEB3 = 'CONNECT_WEB3',
  DISCONNECTED_WEB3 = 'DISCONNECTED_WEB3',
}

export default ActionType;
