enum ActionTypeWeb3 {
  SET_CLAIM_OBJECT = 'SET_CLAIM_OBJECT',
  SET_USER = 'SET_USER',
  SET_ADDRESS = 'SET_ADDRESS',

  SET_SUBSCRIPTION = 'SET_SUBSCRIPTION',
  SUBSCRIBE = 'SUBSCRIBE',
  UNSUBSCRIBE = 'UNSUBSCRIBE',
  SET_CONNECTION = 'SET_CONNECTION',
  CONNECT_WEB3 = 'CONNECT_WEB3',
  DISCONNECTED_WEB3 = 'DISCONNECTED_WEB3',
}

export default ActionTypeWeb3;
